import type { Metadata } from 'next'
import { Indie_Flower } from 'next/font/google'
import './globals.css'

const indieFlower = Indie_Flower({
  subsets: ['latin'],
  variable: '--font-indie-flower',
  weight: ['400']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${indieFlower.className} antialiased`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  )
}
