import type { Metadata } from 'next'
import { Indie_Flower, Playfair_Display } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const indieFlower = Indie_Flower({
  subsets: ['latin'],
  variable: '--font-indie-flower',
  weight: ['400']
})

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  weight: ['400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${indieFlower.className} ${playfairDisplay.variable} ${indieFlower.variable}`} suppressHydrationWarning>
        {children}
        <Toaster position="top-right" expand={false} visibleToasts={5} />
      </body>
    </html>
  )
}
