const SPACE_BASE_URL = process.env.EXPO_PUBLIC_SPACE_ASSETS_BASE_URL;

export const SPACE_ASSETS = {
  star: {
    level_1: `${SPACE_BASE_URL}/star/level_1.png`,
    level_2: `${SPACE_BASE_URL}/star/level_2.png`,
    level_3: `${SPACE_BASE_URL}/star/level_3.png`,
    level_4: `${SPACE_BASE_URL}/star/level_4.png`,
    level_5: `${SPACE_BASE_URL}/star/level_5.png`,
    level_6: `${SPACE_BASE_URL}/star/level_6.png`,
    level_7: `${SPACE_BASE_URL}/star/level_7.png`,
    level_8: `${SPACE_BASE_URL}/star/level_8.png`,
    level_9: `${SPACE_BASE_URL}/star/level_9.png`,
    level_10: `${SPACE_BASE_URL}/star/level_10.png`,
    level_11: `${SPACE_BASE_URL}/star/level_11.png`,
    level_12: `${SPACE_BASE_URL}/star/level_12.png`,
    level_13: `${SPACE_BASE_URL}/star/level_13.png`,
    level_14: `${SPACE_BASE_URL}/star/level_14.png`,
    level_15: `${SPACE_BASE_URL}/star/level_15.png`,
  },
  planet_a: {
    level_1: `${SPACE_BASE_URL}/planet_a/level_1.png`,
    level_2: `${SPACE_BASE_URL}/planet_a/level_2.png`,
    level_3: `${SPACE_BASE_URL}/planet_a/level_3.png`,
    level_4: `${SPACE_BASE_URL}/planet_a/level_4.png`,
    level_5: `${SPACE_BASE_URL}/planet_a/level_5.png`,
    level_6: `${SPACE_BASE_URL}/planet_a/level_6.png`,
    level_7: `${SPACE_BASE_URL}/planet_a/level_7.png`,
    level_8: `${SPACE_BASE_URL}/planet_a/level_8.png`,
    level_9: `${SPACE_BASE_URL}/planet_a/level_9.png`,
    level_10: `${SPACE_BASE_URL}/planet_a/level_10.png`,
    level_11: `${SPACE_BASE_URL}/planet_a/level_11.png`,
    level_12: `${SPACE_BASE_URL}/planet_a/level_12.png`,
    level_13: `${SPACE_BASE_URL}/planet_a/level_13.png`,
    level_14: `${SPACE_BASE_URL}/planet_a/level_14.png`,
    level_15: `${SPACE_BASE_URL}/planet_a/level_15.png`,
  },
  planet_b: {
    level_1: `${SPACE_BASE_URL}/planet_b/level_1.png`,
    level_2: `${SPACE_BASE_URL}/planet_b/level_2.png`,
    level_3: `${SPACE_BASE_URL}/planet_b/level_3.png`,
    level_4: `${SPACE_BASE_URL}/planet_b/level_4.png`,
    level_5: `${SPACE_BASE_URL}/planet_b/level_5.png`,
    level_6: `${SPACE_BASE_URL}/planet_b/level_6.png`,
    level_7: `${SPACE_BASE_URL}/planet_b/level_7.png`,
    level_8: `${SPACE_BASE_URL}/planet_b/level_8.png`,
    level_9: `${SPACE_BASE_URL}/planet_b/level_9.png`,
    level_10: `${SPACE_BASE_URL}/planet_b/level_10.png`,
    level_11: `${SPACE_BASE_URL}/planet_b/level_11.png`,
    level_12: `${SPACE_BASE_URL}/planet_b/level_12.png`,
    level_13: `${SPACE_BASE_URL}/planet_b/level_13.png`,
    level_14: `${SPACE_BASE_URL}/planet_b/level_14.png`,
    level_15: `${SPACE_BASE_URL}/planet_b/level_15.png`,
  },
  planet_c: {
    level_1: `${SPACE_BASE_URL}/planet_c/level_1.png`,
    level_2: `${SPACE_BASE_URL}/planet_c/level_2.png`,
    level_3: `${SPACE_BASE_URL}/planet_c/level_3.png`,
    level_4: `${SPACE_BASE_URL}/planet_c/level_4.png`,
    level_5: `${SPACE_BASE_URL}/planet_c/level_5.png`,
    level_6: `${SPACE_BASE_URL}/planet_c/level_6.png`,
    level_7: `${SPACE_BASE_URL}/planet_c/level_7.png`,
    level_8: `${SPACE_BASE_URL}/planet_c/level_8.png`,
    level_9: `${SPACE_BASE_URL}/planet_c/level_9.png`,
    level_10: `${SPACE_BASE_URL}/planet_c/level_10.png`,
    level_11: `${SPACE_BASE_URL}/planet_c/level_11.png`,
    level_12: `${SPACE_BASE_URL}/planet_c/level_12.png`,
    level_13: `${SPACE_BASE_URL}/planet_c/level_13.png`,
    level_14: `${SPACE_BASE_URL}/planet_c/level_14.png`,
    level_15: `${SPACE_BASE_URL}/planet_c/level_15.png`,
  },
  comet: {
    level_1: `${SPACE_BASE_URL}/comet/level_1.png`,
    level_2: `${SPACE_BASE_URL}/comet/level_2.png`,
    level_3: `${SPACE_BASE_URL}/comet/level_3.png`,
    level_4: `${SPACE_BASE_URL}/comet/level_4.png`,
    level_5: `${SPACE_BASE_URL}/comet/level_5.png`,
    level_6: `${SPACE_BASE_URL}/comet/level_6.png`,
    level_7: `${SPACE_BASE_URL}/comet/level_7.png`,
    level_8: `${SPACE_BASE_URL}/comet/level_8.png`,
    level_9: `${SPACE_BASE_URL}/comet/level_9.png`,
    level_10: `${SPACE_BASE_URL}/comet/level_10.png`,
    level_11: `${SPACE_BASE_URL}/comet/level_11.png`,
    level_12: `${SPACE_BASE_URL}/comet/level_12.png`,
    level_13: `${SPACE_BASE_URL}/comet/level_13.png`,
    level_14: `${SPACE_BASE_URL}/comet/level_14.png`,
    level_15: `${SPACE_BASE_URL}/comet/level_15.png`,
  },
  ufo: {
    level_1: `${SPACE_BASE_URL}/ufo/level_1.png`,
    level_2: `${SPACE_BASE_URL}/ufo/level_2.png`,
    level_3: `${SPACE_BASE_URL}/ufo/level_3.png`,
    level_4: `${SPACE_BASE_URL}/ufo/level_4.png`,
    level_5: `${SPACE_BASE_URL}/ufo/level_5.png`,
    level_6: `${SPACE_BASE_URL}/ufo/level_6.png`,
    level_7: `${SPACE_BASE_URL}/ufo/level_7.png`,
    level_8: `${SPACE_BASE_URL}/ufo/level_8.png`,
    level_9: `${SPACE_BASE_URL}/ufo/level_9.png`,
    level_10: `${SPACE_BASE_URL}/ufo/level_10.png`,
    level_11: `${SPACE_BASE_URL}/ufo/level_11.png`,
    level_12: `${SPACE_BASE_URL}/ufo/level_12.png`,
    level_13: `${SPACE_BASE_URL}/ufo/level_13.png`,
    level_14: `${SPACE_BASE_URL}/ufo/level_14.png`,
    level_15: `${SPACE_BASE_URL}/ufo/level_15.png`,
  },
} as const;

export type SpaceItemType = keyof typeof SPACE_ASSETS;

export const getSpaceAsset = (type: SpaceItemType, level: number) => {
  const assets = SPACE_ASSETS[type];
  const levelKey = `level_${Math.min(15, Math.max(1, level))}` as keyof typeof assets;
  return assets[levelKey] || assets.level_1;
};
